--- # https://docs.openstack.org/install-guide/

# ansible-playbook -b -i hosts main.yml 

- hosts: all
  tasks:
    - include_vars: vars.yml
    - include: environment.yml
    - include: identity.yml
    #- include: environment/main.yml
  handlers:
    - include: handlers.yml
