---

- name: "{{ ansible_distribution }}: Chapter 5.1. Introduction"
  vars:
    msg: |
      Linux From Scratch - Latest Stable
      Chapter Chapter 5.1. Introduction
      http://www.linuxfromscratch.org/lfs/view/stable/chapter05/introduction.html
  debug:
    msg: "{{ msg.split('\n') }}"
